services:
  postgres_db:
    build:
      context: .
      dockerfile: dockerfile.db
    environment:
      POSTGRES_USER: mac
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: AirQualityMonitorDB
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  flask_api:
    build:
      context: .
      dockerfile: dockerfile.api
    container_name: AirQualityMonitorAPI
    environment:
      - DATABASE_URL=postgresql://mac:1234@postgres_db:5432/AirQualityMonitorDB
    ports:
      - "5001:5000"
    depends_on:
      - postgres_db

volumes:
  postgres_data: